/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculator;

import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author L
 */
public class CalculatorForm extends javax.swing.JFrame {

    /**
     * Creates new form CalculatorForm
     */
    public CalculatorForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldNumber1 = new javax.swing.JTextField();
        jTextFieldNumber2 = new javax.swing.JTextField();
        jTextFieldSolution = new javax.swing.JTextField();
        jButtonCalculate = new javax.swing.JButton();
        jCheckBoxSubstract = new javax.swing.JCheckBox();
        jCheckBoxMultiply = new javax.swing.JCheckBox();
        jCheckBoxDivide = new javax.swing.JCheckBox();
        jCheckBoxAdd = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Give numbers to calculate");

        jLabel2.setText("number 1");

        jLabel3.setText("number 2");

        jTextFieldNumber1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNumber1ActionPerformed(evt);
            }
        });

        jTextFieldNumber2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNumber2ActionPerformed(evt);
            }
        });

        jButtonCalculate.setText("calculate");
        jButtonCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalculateActionPerformed(evt);
            }
        });

        jCheckBoxSubstract.setText("substract");
        jCheckBoxSubstract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxSubstractActionPerformed(evt);
            }
        });

        jCheckBoxMultiply.setText("multiply");
        jCheckBoxMultiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMultiplyActionPerformed(evt);
            }
        });

        jCheckBoxDivide.setText("divide");
        jCheckBoxDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxDivideActionPerformed(evt);
            }
        });

        jCheckBoxAdd.setText("add");
        jCheckBoxAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxAddActionPerformed(evt);
            }
        });

        jLabel4.setText("solution");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldNumber1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldNumber2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldSolution, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jButtonCalculate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBoxDivide)
                            .addComponent(jCheckBoxAdd)
                            .addComponent(jCheckBoxMultiply)
                            .addComponent(jCheckBoxSubstract))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jCheckBoxAdd))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextFieldNumber1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextFieldNumber2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBoxSubstract))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldSolution, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jCheckBoxMultiply))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBoxDivide)
                            .addComponent(jButtonCalculate))))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalculateActionPerformed
        // TODO add your handling code here:
        double number1, number2, solution = 0;
        jTextFieldSolution.setText("0");
        try{
            number1 = Double.parseDouble(jTextFieldNumber1.getText());
            number2= Double.parseDouble(jTextFieldNumber2.getText());
            if(number2 == 0 && jCheckBoxDivide.isSelected()) throw new DividieByZeroException();
            if(jTextFieldNumber1.getText().length() > 10 || jTextFieldNumber2.getText().length() > 10) throw new Exception();
            if(jCheckBoxAdd.isSelected()) solution = number1+number2;
            else if(jCheckBoxSubstract.isSelected()) solution = number1-number2;
            else if (jCheckBoxMultiply.isSelected()) solution = number1*number2;
            else if (jCheckBoxDivide.isSelected()) solution = number1/number2;
            else {}
            jTextFieldSolution.setText(String.valueOf(solution));
        } catch (DividieByZeroException ex){
            JOptionPane.showMessageDialog(null, "DividieByZeroException");
        } catch (Exception ex){
            JOptionPane.showMessageDialog(null, "Expresion is not number or is to long or is empty\n", "Number Exception", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonCalculateActionPerformed

    private void jTextFieldNumber2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNumber2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNumber2ActionPerformed

    private void jCheckBoxSubstractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxSubstractActionPerformed
        // TODO add your handling code here:
        if(jCheckBoxSubstract.isSelected()){
            jCheckBoxAdd.setSelected(false);
            jCheckBoxDivide.setSelected(false);
            jCheckBoxMultiply.setSelected(false);
        }
    }//GEN-LAST:event_jCheckBoxSubstractActionPerformed

    private void jCheckBoxDivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxDivideActionPerformed
        // TODO add your handling code here:
        if(jCheckBoxDivide.isSelected()){
            jCheckBoxAdd.setSelected(false);
            jCheckBoxMultiply.setSelected(false);
            jCheckBoxSubstract.setSelected(false);
        }
    }//GEN-LAST:event_jCheckBoxDivideActionPerformed

    private void jTextFieldNumber1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNumber1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNumber1ActionPerformed

    private void jCheckBoxMultiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMultiplyActionPerformed
        // TODO add your handling code here:
        if(jCheckBoxMultiply.isSelected()){
            jCheckBoxAdd.setSelected(false);
            jCheckBoxDivide.setSelected(false);
            jCheckBoxSubstract.setSelected(false);
        }
    }//GEN-LAST:event_jCheckBoxMultiplyActionPerformed

    private void jCheckBoxAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxAddActionPerformed
        // TODO add your handling code here:
        if(jCheckBoxAdd.isSelected()){
            jCheckBoxSubstract.setSelected(false);
            jCheckBoxDivide.setSelected(false);
            jCheckBoxMultiply.setSelected(false);
        }
    }//GEN-LAST:event_jCheckBoxAddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculatorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculatorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculatorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculatorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculatorForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCalculate;
    private javax.swing.JCheckBox jCheckBoxAdd;
    private javax.swing.JCheckBox jCheckBoxDivide;
    private javax.swing.JCheckBox jCheckBoxMultiply;
    private javax.swing.JCheckBox jCheckBoxSubstract;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextFieldNumber1;
    private javax.swing.JTextField jTextFieldNumber2;
    private javax.swing.JTextField jTextFieldSolution;
    // End of variables declaration//GEN-END:variables

    public JTextField getjTextFieldNumber1() {
        return jTextFieldNumber1;
    }

    public void setjTextFieldNumber1(JTextField jTextFieldNumber1) {
        this.jTextFieldNumber1 = jTextFieldNumber1;
    }

    public JTextField getjTextFieldNumber2() {
        return jTextFieldNumber2;
    }

    public void setjTextFieldNumber2(JTextField jTextFieldNumber2) {
        this.jTextFieldNumber2 = jTextFieldNumber2;
    }

    public JTextField getjTextFieldSolution() {
        return jTextFieldSolution;
    }

    public void setjTextFieldSolution(JTextField jTextFieldSolution) {
        this.jTextFieldSolution = jTextFieldSolution;
    }
    
    public JCheckBox getjCheckBoxAdd() {
    return jCheckBoxAdd;
    }

    public void setjCheckBoxAdd(JCheckBox jCheckBoxAdd) {
        this.jCheckBoxAdd = jCheckBoxAdd;
    }
    public JCheckBox getjCheckBoxSubstract() {
    return jCheckBoxSubstract;
    }

    public void setjCheckBoxSubstract(JCheckBox jCheckBoxSubstract) {
        this.jCheckBoxSubstract = jCheckBoxSubstract;
    }
    
    public JCheckBox getjCheckBoxDivide() {
    return jCheckBoxDivide;
    }

    public void setjCheckBoxDivide(JCheckBox jCheckBoxDivide) {
        this.jCheckBoxDivide = jCheckBoxDivide;
    }
    
    public JCheckBox getjCheckBoxMultiply() {
    return jCheckBoxMultiply;
    }

    public void setjCheckBoxMultiply(JCheckBox jCheckBoxMultiply) {
        this.jCheckBoxMultiply = jCheckBoxMultiply;
    }
    
    public JButton getjButtonCalculate() {
    return jButtonCalculate;
    }

    public void setjButtonCalculate(JButton jButtonCalculate) {
        this.jButtonCalculate = jButtonCalculate;
    }
    
}
